# cloudbuild.yaml for admin.amaspc.com

steps:
# Use a standard Node.js image to install the Firebase CLI and deploy
- name: 'node:18'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install -g firebase-tools
      firebase deploy --only hosting --project ama-ecosystem-prod --non-interactive --token $$FIREBASE_TOKEN

# Securely access the Firebase token from Secret Manager
secretEnv: ['FIREBASE_TOKEN']

secrets:
  - secretManager:
      versionName: projects/$PROJECT_ID/secrets/firebase-token/versions/latest
      env: 'FIREBASE_TOKEN'
